  on:
    pull_request:
      branches:
        -main
        -master
    push:
      branches:
        -main
        -master
        -develop
  name: "Build and Release"
  jobs:
    build:
      name: Build & Release
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-java@v1
          with:
            flutter-version: '2.10.4'
        - run: flutter pub get
        - run: flutter clean
        - run: flutter build apk --release --split=per-abi
        - name: Push to Releases
          uses: ncipollo/release-action@v1.10.0
          with:
            artifacts: "build/app/outputs/flutter-apk/*"
            tag: v1.0.${{ github.run_number }}
            token: ${{ secrets.TOKEN }}